[calendars]
  [[icloud]]
    path = /Users/kirkwork/.local/share/khal/icloud/
    color = dark cyan
    readonly = false

[caldav]
  [[icloud]]
    url = https://caldav.icloud.com
    user = cantstayblue@gmail.com
    password = strn-gllk-odct-vtyx
    # sync the calendar collection into the 'icloud' calendar
    calendar = icloud
