[general]
status_path = /Users/kirkwork/.vdirsyncer/status/

[pair icloud]
a = icloud_local
b = icloud_remote
collections = ["from a"]

[storage icloud_local]
type = filesystem
path = /Users/kirkwork/.local/share/khal/icloud/
fileext = .ics

[storage icloud_remote]
type = caldav
url = https://caldav.icloud.com
username = cantstayblue@gmail.com
password = strn-gllk-odct-vtyx
